spring:
  application:
    name: merchandize
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
#      image:
#        options:
#          model: dall-e-3
#          size: 1024x1024
#          style: vivid
#          quality: standard
#          response_format: url
      audio:
        transcription:
          options:
            model: whisper-1
            language: en
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

image-directory: "/home/wyatthlang/Downloads/"